import assert from "node:assert/strict";
import { ChainStore } from "./state.js";
import { startEntryTrace, observedCandidate, releaseTrace, finalDecisionEvidence, brokerTrace, safeTrace, traceHealth } from "./decisionTrace.js";
import { ObservationQueue } from "./observationQueue.js";
import { readDecisionStageEvidence } from "../../lib/research/decisionStageEvidence";
import type { ShadowDecision } from "./decide.js";
const oldNow = Date.now; let now = 1000000; Date.now = () => now;
const chain = new ChainStore();
const quote = { occ: "SPY260908C00700000", strike: 700, optType: "call" as const, expiration: "2026-09-08", bid:1.50, ask:1.55, mid:1.525,last:null,delta:null,providerQuoteAt:new Date(now-4000).toISOString(),bidSize:0,askSize:3,feed:"opra" };
chain.seed([quote]);const initial=chain.quoteObservation(quote.occ,now);assert.equal(initial.providerAgeMs,4000);assert.equal(initial.bidSize,0);
now+=180000;chain.update([]);assert.equal(chain.ageMs,0);const retained=chain.quoteObservation(quote.occ,now);assert.equal(retained.localAgeMs,180000);assert.equal(retained.presentInLatestRefresh,false);assert.equal(retained.latestRefreshCount,0);assert.equal(chain.byOcc(quote.occ),quote);
chain.update([{...quote,occ:"OTHER"}]);assert.equal(chain.quoteObservation(quote.occ,now).presentInLatestRefresh,false);
assert.equal(chain.quoteObservation("MISSING",now).lookupStatus,"missing");
chain.update([{...quote,providerQuoteAt:new Date(now+1000).toISOString()}]);assert.equal(chain.quoteObservation(quote.occ,now).providerClockInFuture,true);
const common={chain,occ:quote.occ,sourceBarAtMs:900000,quoteQueried:true,quoteAtMs:1000000,quote:initial,sizingVisited:true,qty:2,sizingInputUsd:210,stopFraction:.5,nativeStopPct:50,blocked:null};
const d: ShadowDecision={slug:"vb-macd-state",status:"armed",action:"enter",reason:"test",qty:2,detail:{ask:1.55,decisionTrace:startEntryTrace(common)}};
const selectedBefore=JSON.stringify(d);
let observed=observedCandidate(d,1001000);const prepared={...observed,qty:4,detail:{...observed.detail,decisionTrace:releaseTrace(observed,{qty:4,premiumCap:1.75,debitCapUsd:700,observedAtMs:1002000})}};
let final=finalDecisionEvidence(prepared,null);let trace=final.detail!.decisionTrace as any;
assert.equal(trace.quantities.provisionalQty,2);assert.equal(trace.quantities.releaseRequestedQty,4);assert.equal(trace.quantities.postArbitrationQty,4);assert.equal(trace.quantities.submittedQty,null);assert.equal(trace.sizing.requestedNominalStopUsd,310);assert.equal(JSON.stringify(d),selectedBefore);
assert.equal((finalDecisionEvidence(prepared,"capacity").detail!.decisionTrace as any).quantities.postArbitrationQty,0);
const unqueried=startEntryTrace({...common,quoteQueried:false,quoteAtMs:null,quote:null,sizingVisited:false,qty:0,blocked:"daily_stop"})!;assert.equal(unqueried.selectedQuote.ask,null);assert.equal(unqueried.quantities.provisionalQty,null);assert.equal(unqueried.gates[1].status,"not_evaluated");
const noQuote=startEntryTrace({...common,quote:{lookupStatus:"missing",ask:null},sizingVisited:false,qty:0,blocked:"no_quote"})!;assert.equal(noQuote.gates[1].status,"pass");
const submission=chain.quoteObservation(quote.occ,now);chain.update([{...quote,ask:2.5}]);
const partial=brokerTrace(final,chain,quote.occ,4,now+1000,"result",now,{filledQty:2,fill:1.56,status:"partially_filled"},submission)!;
assert.equal(partial.selectedQuote.ask,1.55);assert.equal(partial.submissionQuote!.ask,1.55);assert.equal(partial.quantities.submittedQty,4);assert.equal(partial.quantities.filledQty,2);assert.equal(partial.sizing.filledNominalStopUsd,156);assert.equal(partial.clocks.exchangeFillAtMs,null);
const error=brokerTrace(final,chain,quote.occ,4,now+1000,"error",now,undefined,submission)!;assert.equal(error.quantities.filledQty,null);assert.equal(error.quantities.submittedQty,null);assert.equal(error.quantities.submissionAttemptedQty,4);assert.equal(error.brokerState,"submission_attempted_result_unknown");
const dedup=brokerTrace(final,chain,quote.occ,4,now,"not_submitted",null)!;assert.equal(dedup.quantities.submittedQty,0);assert.equal(dedup.quantities.filledQty,null);
assert.equal(readDecisionStageEvidence({filled_qty:0,payload:{}}).state,"unavailable");
const read=readDecisionStageEvidence({filled_qty:0,payload:{decisionDetail:{decisionTrace:error}}});assert.equal(read.state,"observed");if(read.state==='observed')assert.equal(read.quantities.filledQty,null);
assert.equal(safeTrace(()=>{throw Error('fixture')}),undefined);assert.ok(traceHealth.constructionFailed>0);
assert.equal(safeTrace(()=>({...trace,identity:{large:'x'.repeat(13000)}})),undefined);assert.ok(traceHealth.oversized>0);
Date.now=oldNow;
async function queues(){
 let release!:()=>void;const stuck=new Promise<void>(r=>release=r);
 const q=new ObservationQueue<{id:string,event_at?:string}>(async()=>{await stuck;return 'written'},2,2);
 assert.equal(q.enqueue({id:'a',event_at:'2026-09-06'}),true);assert.equal(q.enqueue({id:'a'}),true);assert.equal(q.enqueue({id:'b',event_at:'2026-09-07'}),true);assert.equal(q.enqueue({id:'c'}),false);assert.equal(q.counters.pending,2);assert.equal(q.counters.duplicate,1);assert.equal(q.counters.overflowDropped,1);
 release();await q.drained();assert.equal(q.counters.pending,0);assert.equal(q.counters.written,2);
 const failed=new ObservationQueue<{id:string}>(async()=>{throw Error('sink')});failed.enqueue({id:'f'});await failed.drained();assert.equal(failed.counters.writeFailed,1);assert.equal(failed.counters.pending,0);
 const outcomes=new ObservationQueue<{id:string}>(async r=>r.id as 'missingTable'|'noServiceRole'|'duplicate');for(const id of ['missingTable','noServiceRole','duplicate'])outcomes.enqueue({id});await outcomes.drained();assert.equal(outcomes.counters.missingTable,1);assert.equal(outcomes.counters.noServiceRole,1);assert.equal(outcomes.counters.duplicate,1);
 const load=new ObservationQueue<{id:string}>(async()=> 'written');const start=performance.now();for(let i=0;i<700;i++)load.enqueue({id:String(i)});const enqueueMs=performance.now()-start;assert.equal(load.counters.pending,512);assert.equal(load.counters.overflowDropped,188);await load.drained();assert.equal(load.counters.written,512);
 console.log(JSON.stringify({result:'PASS',queueBurst:700,accepted:512,overflow:188,enqueueMs,traceCases:'quote loss/empty refresh, sizing override, blocked/unqueried, partial/error/dedup, immutable snapshots, reader nulls, construction failure and queue fault cases'}));
}
queues().catch(e=>{console.error(e);process.exitCode=1});
