import assert from "node:assert/strict";
import { fixedCoverageHarness } from "./fixedEntryCoverage.fixtures.js";
import { coordinateFixedCommand } from "./fixedEntryCommandCoordinator.js";
import { materializeFixedEntryCoverage } from "./fixedEntryCoverageMaterialization.js";
import { requestFixedIntentExit } from "./fixedEntryExitRequest.js";
import { bookFixedSellCommand } from "./fixedEntrySellBooking.js";
import { buildFixedEntryReporting } from "./fixedEntryReporting.js";
import { fixedLedgerId } from "./fixedEntryLedgerModel.js";
import { isFixedEntryProtocolObservation } from "../../lib/research/fixedEntryProtocolEvidence.js";
async function main() {
  const h = fixedCoverageHarness();
  const project = async () => buildFixedEntryReporting(h.intent, await h.coverage.snapshot(h.intent));
  await coordinateFixedCommand(h.commandPorts, h.intent, h.buy);
  const initial = (await materializeFixedEntryCoverage(h.coverage, h.intent)).position!;
  const partial = await project();
  assert.equal(partial.pendingCommands, 1);
  assert.equal(partial.execution.filter(r => r.event_kind === "broker_result").length, 0, "partial floor never occupies terminal broker evidence ID");
  assert.equal(partial.outcomes[0].quantity, 2);
  assert.equal(partial.outcomes[0].avg_entry_price, 2);
  assert.ok(partial.cohorts[0].censorCode);
  const openSnapshot = await h.coverage.snapshot(h.intent);
  assert.throws(() => buildFixedEntryReporting(h.intent, { ...openSnapshot, positions: [] }), /durable_coverage_row_missing/);
  const changedOpen = structuredClone(openSnapshot); changedOpen.positions[0].qty = 3;
  assert.throws(() => buildFixedEntryReporting(h.intent, changedOpen), /open_row_evidence_mismatch/);
  const falseClose = structuredClone(openSnapshot);
  Object.assign(falseClose.positions[0], { status: "closed", current_mark: 99, realized_pnl: 19400,
    closed_at: "2026-09-08T14:30:05Z", close_reason: "invented_close" });
  assert.throws(() => buildFixedEntryReporting(h.intent, falseClose), /closed_booking_readback_mismatch/);
  await requestFixedIntentExit(h.coverage.storage, h.intent, { source: "native-manager", reason: "stop_premium",
    requestedAt: new Date(h.coverage.now()).toISOString() });
  const sell = h.makeClaim("sell", 0, 2, initial);
  await coordinateFixedCommand(h.commandPorts, h.intent, sell);
  assert.equal((await project()).outcomes.filter(r => r.event_kind === "position_booked").length, 0, "a terminal sell is not yet a booked outcome");
  await bookFixedSellCommand(h.bookPorts, h.intent, sell.command.id);
  const firstClose = await project();
  assert.equal(firstClose.outcomes.find(r => r.event_kind === "position_booked")?.realized_pnl, -200);
  assert.deepEqual(firstClose.outcomes.find(r => r.event_kind === "position_opened"), partial.outcomes[0]);
  await h.lateBuy();
  const second = (await materializeFixedEntryCoverage(h.coverage, h.intent)).position!;
  const late = await project();
  const remainder = late.outcomes.find(r => r.event_kind === "position_remainder_opened")!;
  assert.equal(remainder.parent_position_id, initial.id);
  assert.equal(remainder.quantity, 2); assert.equal(remainder.avg_entry_price, 4);
  assert.equal(remainder.opportunity_id, partial.outcomes[0].opportunity_id);
  assert.equal(late.execution.filter(r => r.action === "enter" && r.event_kind === "decision").length, 1);
  assert.equal(late.execution.filter(r => r.action === "enter" && r.event_kind === "broker_result").length, 1);
  const terminalBuy = late.execution.find(r => r.action === "enter" && r.event_kind === "broker_result")!;
  assert.equal(terminalBuy.filled_qty, 4); assert.equal(terminalBuy.fill_price, 3);
  assert.equal((terminalBuy.payload.fixedCommandEvidence as { submittedAt: unknown }).submittedAt, null);
  const secondSell = h.makeClaim("sell", 1, 2, second);
  await coordinateFixedCommand(h.commandPorts, h.intent, secondSell);
  await bookFixedSellCommand(h.bookPorts, h.intent, secondSell.command.id);
  const complete = await project();
  assert.equal(complete.pendingCommands, 0);
  assert.equal(complete.outcomes.filter(r => r.event_kind === "position_booked").reduce((n,r) => n + r.realized_pnl!,0), -800);
  assert.equal(complete.execution.filter(r => r.action === "exit" && r.event_kind === "decision").length, 1);
  assert.equal(new Set(complete.execution.filter(r => r.action === "exit").map(r => r.trace_id)).size, 1);
  assert.ok(complete.cohorts.every(r => r.censorCode));
  assert.ok(complete.execution.every(r => !isFixedEntryProtocolObservation(r)));
  assert.deepEqual(await project(), complete, "restart replay produces identical complete evidence");
  const snapshot = await h.coverage.snapshot(h.intent);
  assert.throws(() => buildFixedEntryReporting(h.intent, { ...snapshot, positions: snapshot.positions.slice(1) }), /incomplete_row_lineage/);
  assert.throws(() => buildFixedEntryReporting(h.intent, { ...snapshot, records: snapshot.records.filter(r => r.id !== fixedLedgerId("coverage", [initial.id,0])) }), /first_coverage/);
  const corrupt = structuredClone(snapshot); corrupt.positions[0].realized_pnl = 999;
  assert.throws(() => buildFixedEntryReporting(h.intent, corrupt), /closed_booking_readback_mismatch/);
  const changedTime = structuredClone(snapshot); changedTime.positions[0].opened_at = "2026-09-08T14:30:04Z";
  assert.throws(() => buildFixedEntryReporting(h.intent, changedTime), /first_coverage_hash_mismatch/);
  // The original opening is unchanged when quantity/basis grow in the same row.
  const growth = fixedCoverageHarness(); await coordinateFixedCommand(growth.commandPorts, growth.intent, growth.buy);
  await materializeFixedEntryCoverage(growth.coverage, growth.intent);
  const originalGrowthRow = structuredClone([...growth.positions.values()][0]);
  const before = buildFixedEntryReporting(growth.intent, await growth.coverage.snapshot(growth.intent));
  await growth.lateBuy(); await materializeFixedEntryCoverage(growth.coverage, growth.intent);
  const after = buildFixedEntryReporting(growth.intent, await growth.coverage.snapshot(growth.intent));
  assert.deepEqual(after.outcomes, before.outcomes);
  assert.deepEqual(after.cohorts, before.cohorts);
  const latestGrowth = await growth.coverage.snapshot(growth.intent);
  assert.throws(() => buildFixedEntryReporting(growth.intent, { ...latestGrowth, positions: [originalGrowthRow] }), /stale_current_row/);
  // A delayed first row does not erase an earlier observed partial fill.
  const delayed = fixedCoverageHarness(); await coordinateFixedCommand(delayed.commandPorts, delayed.intent, delayed.buy);
  await delayed.lateBuy(); await materializeFixedEntryCoverage(delayed.coverage, delayed.intent);
  const delayedReport = buildFixedEntryReporting(delayed.intent, await delayed.coverage.snapshot(delayed.intent));
  assert.equal(delayedReport.cohorts[0].position.qty, 4);
  assert.ok(delayedReport.cohorts[0].censorCode);
  const zero = fixedCoverageHarness(); await coordinateFixedCommand(zero.commandPorts,zero.intent,zero.buy);
  const zeroRow = (await materializeFixedEntryCoverage(zero.coverage,zero.intent)).position!;
  await requestFixedIntentExit(zero.coverage.storage,zero.intent,{source:"native-manager",reason:"stop_premium",
    requestedAt:new Date(zero.coverage.now()).toISOString()});
  const zeroSell = zero.makeClaim("sell",0,2,zeroRow);
  zero.commandPorts.reserveSell = async () => ({state:"lost-race",row:null});
  assert.equal((await coordinateFixedCommand(zero.commandPorts,zero.intent,zeroSell)).reason,"row-reservation-failed");
  assert.equal((await bookFixedSellCommand(zero.bookPorts,zero.intent,zeroSell.command.id)).state,"booked");
  const zeroPlan = buildFixedEntryReporting(zero.intent,await zero.coverage.snapshot(zero.intent));
  assert.equal(zeroPlan.outcomes.filter(r => r.event_kind === "position_booked").length,0);
  assert.equal(zeroPlan.execution.filter(r => r.event_kind === "broker_result").length,0);
  console.log("fixedEntryReporting: PASS · terminal-only evidence, stable original decision/opening, two-generation lineage, exact booked economics, explicit partial-cohort censor and restart replay");
}
void main().catch(e => { console.error(e); process.exitCode = 1; });
