import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { deploymentTarget, resolvePresentation } from "./presentation";

assert.equal(deploymentTarget("production"), "production");
assert.equal(deploymentTarget("preview"), "preview");
assert.equal(deploymentTarget("development"), "development");
assert.equal(deploymentTarget(undefined), "development");
assert.equal(resolvePresentation("909", "production"), "909");
assert.equal(resolvePresentation("folio", "production"), "909");
assert.equal(resolvePresentation("folio", "preview"), "folio");
assert.equal(resolvePresentation("folio", "development"), "folio");

const mobileShell = readFileSync("components/mobile2/MobileShell.tsx", "utf8");
const ledDisplay = readFileSync("components/console/hw/LedDisplay.tsx", "utf8");
const shadowResearch = readFileSync("components/perform/ShadowResearchWorkspace.tsx", "utf8");
const foundationCss = readFileSync("app/seve-909.css", "utf8");
const workstationCss = readFileSync("app/workstation.css", "utf8");
const workstationShell = readFileSync("components/shell/WorkstationShell.tsx", "utf8");
const performCss = readFileSync("app/perform.css", "utf8");
const intradayChart = readFileSync("components/IntradayChart.tsx", "utf8");
const mobilePerform = readFileSync("components/mobile2/MobilePerform.tsx", "utf8");
const mobileDock = readFileSync("components/mobile2/MobileDock.tsx", "utf8");
const mobileRackRow = readFileSync("components/mobile2/MobileRackRow.tsx", "utf8");
const mobileStudio = readFileSync("components/mobile2/MobileStudio.tsx", "utf8");
const sessionSequencer = readFileSync("components/console/SessionSequencer.tsx", "utf8");
const mobileCss = readFileSync("app/mobile2.css", "utf8");
assert.match(mobileShell, /<LedWordmark value="\$EVE" color=\{dayColor\}/);
assert.match(mobileShell, /const dayColor = down \? "var\(--led-red\)" : "var\(--pm-green\)"/);
assert.match(ledDisplay, /"\$": "afgcd"[\s\S]*"E": "afged"[\s\S]*"V": ""/);
assert.match(mobileShell, /className="m2-status-center"/);
assert.doesNotMatch(mobileShell, /className="m2-band"/);
assert.match(shadowResearch, /const RECENT_SESSION_LIMIT = 4/);
assert.match(shadowResearch, /aria-label="Older research session"/);
assert.match(shadowResearch, /shadowResearch\.sessions\.slice\(RECENT_SESSION_LIMIT\)/);
assert.match(foundationCss, /\[data-skin="cream"\] \.m2-book-nav button/);
assert.match(foundationCss, /\[data-skin="cream"\] \.m2-markets-chain > \.panel/);
assert.match(workstationCss, /\.ws-deck-mode,\.ws-transport \{ display:none; \}/);
assert.match(workstationCss, /\.ws-left-copy b\{[^}]*font-size:12px/);
assert.match(workstationCss, /\.ws-left-copy small\{[^}]*font-size:10px/);
assert.match(workstationCss, /:is\(\.pf-market-target,\.pf-markets-chart\) \.phead \.t \{ font-size:13px/);
assert.match(workstationCss, /:is\(\.pf-market-target,\.pf-markets-chart\) :is\(\.chart-toggle,\.seg\) button \{ min-height:28px/);
assert.match(workstationCss, /\.ws-telemetry \.acct-switch \{[^}]*grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);
assert.match(workstationCss, /\.ws-telemetry \.acct-switch \{[^}]*height:32px/);
assert.match(workstationCss, /\.ws-telemetry \.acct-opt \{[^}]*height:32px/);
assert.match(workstationCss, /\.ws-metric\.pos>span\{color:var\(--hw-green,#55d766\)\}/);
assert.match(workstationCss, /\.ws-metric\.neg>span\{color:var\(--hw-red-soft,#ff6044\)\}/);
assert.match(workstationShell, /const startOfDayNav = liveFund\.nav - liveFund\.dayPnl/);
assert.match(workstationShell, /const dayPnlPct = startOfDayNav > 0 \? \(liveFund\.dayPnl \/ startOfDayNav\) \* 100 : null/);
assert.doesNotMatch(workstationShell, /dayChangePct/);
assert.doesNotMatch(workstationShell, /selectedAccount\?\.mode/);
assert.match(workstationShell, /ws-metric ws-metric--led"><small>DESK CAPACITY/);
assert.match(workstationShell, /ws-metric ws-metric--led"><small>OPEN POSITIONS/);
assert.match(workstationShell, /ws-metric ws-metric--led"><small>RISK USED/);
assert.match(performCss, /grid-auto-flow: column; grid-auto-columns: minmax\(182px, 1fr\)/);
assert.match(intradayChart, /hideTitle = false/);
assert.match(mobilePerform, /onSymbolChange=\{setSymbol\}[\s\S]*hideTitle/);
assert.ok(mobileRackRow.indexOf('className="m2-fireslbl') < mobileRackRow.indexOf("m2-passport lane-"));
assert.ok(mobileRackRow.indexOf("m2-passport lane-") < mobileRackRow.lastIndexOf("<ChannelConfigDraftPanel"));
assert.match(mobileRackRow, /className="m2-passport-toggle"[\s\S]*aria-expanded=\{passportOpen\}/);
assert.match(mobileStudio, /className="m2-studio-sequencer"/);
assert.doesNotMatch(mobileStudio, /m2-tape-screen/);
assert.doesNotMatch(mobileStudio, /MASTER · SESSION/);
assert.doesNotMatch(mobileStudio, /Runtime release identity/);
assert.match(mobileDock, /onOpenChannel\?: \(slug: string\) => void/);
assert.match(mobileDock, /aria-label=\{`Open \$\{ch\.slug\} in Studio`\}/);
assert.match(mobileShell, /const openStudioChannel = \(slug: string\) => \{[\s\S]*setOpenSlug\(slug\);[\s\S]*setRoom\("studio"\)/);
assert.match(mobileCss, /\.m2-studio-sequencer \.m-sqbody \{[^}]*padding-top:6px/);
assert.match(sessionSequencer, /if \(variant === "dock"\)[\s\S]*className="m-sqbody"[\s\S]*className="m-sqhead"/);
assert.match(mobileCss, /\.m2-app\[data-room="studio"\] \.m2-padbar \{ margin-top:0/);
assert.match(foundationCss, /\[data-skin="blackout"\] \.m2-desk-section > header,[\s\S]{0,180}\.m2-desk-disclosure > summary/);
assert.match(foundationCss, /\.m2-market-switch button \{[\s\S]{0,120}min-height:\s*46px/);
assert.match(foundationCss, /\.m2-chart-body :is\(\.chart-toggle, \.seg\) button \{[\s\S]{0,120}min-height:\s*42px/);
assert.match(foundationCss, /\.srw-head b \{[\s\S]{0,60}font-size:\s*16px/);
assert.match(foundationCss, /\.srw-row \{[\s\S]{0,80}min-height:\s*40px;[\s\S]{0,60}font-size:\s*12\.5px/);
assert.match(foundationCss, /:is\(\s*\.pf-market-target,\s*\.pf-markets-chart\s*\) :is\([\s\S]{0,100}\.chart-toggle,[\s\S]{0,60}\.seg[\s\S]{0,40}\) button\.on/);

console.log("presentation-selftest: 57/57 passed");
