import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { DEFAULT_SEVE_THEME, cssVariablesForTheme, validateSeveTheme, type ThemeMode } from "../lib/theme/seveTheme";

const validation = validateSeveTheme(DEFAULT_SEVE_THEME);
if (!validation.valid) throw new Error(`SEVE theme is invalid:\n${validation.errors.join("\n")}`);

const selector = (mode: ThemeMode) =>
  `html body .console-root.console-root[data-theme="${mode}"],\n`
  + `html body .console-root[data-theme="${mode}"] .shell-root.ws909[data-skin="${mode}"],\n`
  + `html body .console-root[data-theme="${mode}"] .m2-app[data-skin="${mode}"]`;

const block = (mode: ThemeMode) => {
  const variables = cssVariablesForTheme(DEFAULT_SEVE_THEME, mode);
  return `${selector(mode)} {\n${Object.entries(variables).map(([name, value]) => `  ${name}: ${value};`).join("\n")}\n}`;
};

const output = `/* AUTO-GENERATED by npm run theme:generate.
   Source: design-tokens/seve-909.json. Do not hand-edit. */

${block("cream")}

${block("blackout")}
`;

async function main() {
  await writeFile(resolve("app/seve-theme.generated.css"), output, "utf8");
  console.log("wrote app/seve-theme.generated.css");
}

void main();
