import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const source = readFileSync(new URL("./nightly-decision-atlas.ts", import.meta.url), "utf8");
assert.match(source, /profitability-ledger\.ts/);
assert.match(source, /decision-atlas\.ts/);
assert.match(source, /entry-atlas\.ts/);
assert.match(source, /channel-trail-frontier\.ts/);
assert.match(source, /weekly-readout\.ts/);
assert.match(source, /channel-decision-briefs\.ts/);
assert.match(source, /nightly-channel-learning\.ts/);
assert.match(source, /--shadow-catchup-manifest/);
assert.doesNotMatch(source, /capture-forward|launchctl|cron|\.from\(|insert\(|upsert\(/);
assert.match(source, /after-close workflow/);
assert.match(source, /independently verified/);
assert.match(source, /--virtual-catchup-file/);
assert.match(source, /--virtual-catchup-manifest/);
assert.match(source, /--trail-file/);
assert.match(source, /--entry-atlas-file/);
assert.match(source, /must be supplied together/);
console.log("nightly-decision-atlas-selftest: PASS");
