import assert from 'node:assert/strict';
import { heldTradePeakObservation, summarizePeakDiagnostics, validatedNarrative } from '../../supabase/functions/_shared/reportingEvidence';
const row = (entry: number, peak: number | null, pnl: number, qty = 2) => ({avg_entry_price:entry, peak_mark:peak, realized_pnl:pnl, qty});
assert.equal(heldTradePeakObservation('above', [row(1,1.2,41)]).issue, 'exit_above_sampled_peak');
assert.equal(heldTradePeakObservation('missing', [row(1,null,20)]).issue, 'missing_tranche_peak');
assert.equal(heldTradePeakObservation('zero', [row(1,1,0,0)]).issue, 'invalid_tranche_economics');
const valid = heldTradePeakObservation('split', [row(1,1.5,20,1),row(1,1.5,-10,1)]);
assert.equal(valid.realizedUsd, 10); assert.equal(valid.peakGainUsd,100);
const summary=summarizePeakDiagnostics([valid,heldTradePeakObservation('above',[row(1,1.2,41)]),heldTradePeakObservation('flat',[row(1,1,0)])]);
assert.equal(summary.total,3);assert.equal(summary.valid,1);assert.equal(summary.excluded,2);assert.equal(summary.retainedPct,10);
assert.equal(summarizePeakDiagnostics([heldTradePeakObservation('loss',[row(1,1.5,-50)])]).retainedPct,null,'negative returns cannot be presented as retained gains');
assert.equal(summarizePeakDiagnostics([heldTradePeakObservation('flat',[row(1,1,0)])]).retainedPct,null,'zero denominator never means 100%');
assert.equal(summarizePeakDiagnostics([]).retainedPct,null);
assert.equal(validatedNarrative({weekSummary:'Bad </parameter> output'},'weekly'),null);
assert.equal(validatedNarrative({channels:'[{"slug":"bad"}]'},'weekly'),null);
assert.equal(validatedNarrative({channels:[{slug:'a',note:{bad:true}}]},'weekly'),null);
assert.ok(validatedNarrative({weekSummary:'Observed facts.',channels:[{slug:'a',verdict:'watch',note:'Limited sample'}],keyLearnings:['Native stops retained.']},'weekly'));
assert.ok(validatedNarrative({marketSummary:'Facts',channels:[{slug:'a',wentRight:['One result']}],systemFindings:[],topActions:[]},'daily'));
console.log('reporting-evidence-selftest: PASS');
